/* ════════════════════════════════════════════════════════════
   KATHIRAVAN V — VERIFIED CREDENTIALS DATA ENGINE
   Primary Source of Truth: Uploaded Certificates & CV Documents
   ════════════════════════════════════════════════════════════ */

const CERTIFICATES_DATA = [
  {
    id: "guvi-google-ai",
    title: "Build & Deploy Apps with Google AI Studio & Multilingual AI Speech App",
    organization: "GUVI Geek Networks (IITM Research Park) x HCL x Google for Education",
    category: "TECHNICAL",
    type: "Featured Achievement",
    date: "April 2, 2026",
    duration: "Intensive Hands-on Build",
    role: "AI Developer / Student Participant",
    achievement: "Successfully built & deployed AI applications using Google AI Studio and Vibe Coding",
    description: "Awarded for completing the practical build track on creating and deploying AI-powered applications with Google AI Studio and developing multilingual AI speech tools.",
    skills: ["Google AI Studio", "Vibe Coding", "Multilingual Speech AI", "App Deployment", "Generative AI"],
    credentialId: "51lg0783Ud9779P294",
    verificationUrl: "https://www.guvi.in/certificate?id=51lg0783Ud9779P294",
    image: "certificates/HCL GUVI Certification - 511g0783Ud9779PZ94.png",
    relatedProject: "AXON / HealthSync",
    featured: true
  },
  {
    id: "pecteam-appreciation-award",
    title: "Appreciation Award — RYDEX IoT Smart Helmet (PECTEAM 2K26)",
    organization: "Panimalar Engineering College (Autonomous Institution, Anna Univ)",
    category: "ACHIEVEMENT",
    type: "Project Appreciation Award",
    date: "April 21, 2026",
    duration: "Project Contest & Poster Presentation",
    role: "Lead Hardware Innovator (ECE Dept)",
    achievement: "Awarded Appreciation Award for engineering the RYDEX Smart Helmet system for accident detection and rider safety",
    description: "Awarded during PECTEAM 2K26 for building the RYDEX IoT safety system integrating ESP32, MQ-3 alcohol sobriety lockout, MPU6050 crash detection, and GPS/GSM Telegram alerts.",
    skills: ["IoT Safety", "ESP32", "Hardware Prototyping", "Poster Award", "Public Safety Tech"],
    credentialId: "PECTEAM-2K26-RYDEX",
    verificationUrl: "",
    image: "certificates/compatitions/IMG_20260421_192952.jpg",
    relatedProject: "RYDEX Smart Helmet",
    featured: true
  },
  {
    id: "tritoconnect-pcb-internship",
    title: "PCB DESIGN Internship & Hands-on Hardware Certification",
    organization: "Tritoconnect Technologies & Project Services (MSME Govt. of India)",
    category: "INTERNSHIP",
    type: "Industry Internship",
    date: "April 10, 2026 – April 24, 2026",
    duration: "15 Days Intensive",
    role: "Hardware & PCB Design Intern",
    achievement: "Gained hands-on industrial experience in schematic creation, DRC/ERC, component layout, and PCB manufacturing",
    description: "Completed practical industrial internship at Tritoconnect Technologies focusing on PCB schematic design, component placement, design rule checks, and hardware prototyping.",
    skills: ["PCB Design", "Schematic Capture", "DRC / ERC Checks", "Component Placement", "Hardware Prototyping", "Electronics"],
    credentialId: "TC-PCB-2026-KATHIR",
    verificationUrl: "",
    image: "certificates/internship.jpg",
    relatedProject: "RYDEX Smart Helmet",
    featured: true
  },
  {
    id: "cii-hp-applied-ml",
    title: "Foundational Course on Applied Machine Learning and AI",
    organization: "Confederation of Indian Industry (CII) & HP (NCVET Recognised)",
    category: "TECHNICAL",
    type: "Professional Certification",
    date: "September 17, 2026",
    duration: "193.4 Hours",
    role: "Student Trainee",
    achievement: "Cleared NCVET-recognised rigorous national assessment in Applied ML and AI",
    description: "Comprehensive 193.4-hour certification program delivered by CII Centre of Excellence in partnership with HP, covering foundational applied machine learning, neural models, and AI workflow design.",
    skills: ["Applied Machine Learning", "Artificial Intelligence", "Model Evaluation", "Data Analytics", "NCVET Certified"],
    credentialId: "23CII-FJ26-61632",
    verificationUrl: "",
    image: "certificates/pdf_img_Foundational Course on Applied Machine Learning and A_p1_0.png",
    relatedProject: "Replenova",
    featured: true
  },
  {
    id: "hackerrank-python-basic",
    title: "Python (Basic) Skill Certification",
    organization: "HackerRank",
    category: "TECHNICAL",
    type: "Standardized Skill Test",
    date: "July 26, 2026",
    duration: "Skill Assessment Test",
    role: "Certified Candidate",
    achievement: "Passed HackerRank standardized technical skill assessment for Python programming",
    description: "Verified skill assessment credential confirming proficiency in Python programming syntax, algorithms, data structures, and problem-solving.",
    skills: ["Python", "Algorithms", "Data Structures", "Problem Solving"],
    credentialId: "S4D030DZCE93",
    verificationUrl: "https://www.hackerrank.com/certificates/S4D030DZCE93",
    image: "certificates/pdf_img_python_basic certificate(hacker_rank)_p1_0.png",
    relatedProject: "Level Up V2",
    featured: true
  },
  {
    id: "novitech-fullstack-masterclass",
    title: "30 Days MasterClass in Full Stack Development",
    organization: "NoviTech R&D Private Limited (ISO 9001:2015 Certified)",
    category: "TECHNICAL",
    type: "MasterClass Certification",
    date: "February 12 – March 19, 2026",
    duration: "30 Days",
    role: "Trainee Developer",
    achievement: "Mastered full stack web architecture, frontend styling, backend routing, and database integration",
    description: "30-day intensive masterclass covering frontend building blocks, backend service integration, RESTful APIs, and full stack deployment practices.",
    skills: ["Full Stack Development", "HTML5/CSS3", "JavaScript", "REST APIs", "Web Architecture"],
    credentialId: "NT BGOFSDET20",
    verificationUrl: "",
    image: "certificates/fullstrack development.jpg",
    relatedProject: "Panimalar Smart Bus Transport",
    featured: false
  },
  {
    id: "excelr-python-fullstack",
    title: "Certificate Program in Python Full Stack",
    organization: "ExcelR EdTech Pvt. Ltd.",
    category: "TECHNICAL",
    type: "Professional Certification",
    date: "April 23, 2026",
    duration: "Comprehensive Program",
    role: "Full Stack Trainee",
    achievement: "Completed future-ready curriculum in Python-driven full stack development",
    description: "Professional certification program equipping participants with essential skills in Python, web application design, database connectivity, and deployment.",
    skills: ["Python", "Full Stack Web", "Database Management", "Backend Engineering"],
    credentialId: "78774",
    verificationUrl: "",
    image: "certificates/python full strack.jpg",
    relatedProject: "Level Up",
    featured: false
  },
  {
    id: "microsoft-sora-ai",
    title: "SOAR - AI to be Aware (National Skills Qualification Framework)",
    organization: "Microsoft & NCVET (Skill India Initiative)",
    category: "WORKSHOPS",
    type: "Govt & Corporate Certification",
    date: "April 3, 2026",
    duration: "20 Hours (0.5 Credits, NSOF Level 3)",
    role: "Certified Participant",
    achievement: "Assessed and cleared national competency in AI awareness and generative media technologies",
    description: "National skill competency certificate issued by Microsoft and NCVET recognizing completion of training in generative AI, Sora AI video synthesis, and AI safety awareness.",
    skills: ["Generative AI", "Sora AI", "AI Ethics & Safety", "NSOF Level 3", "Microsoft Skill India"],
    credentialId: "2026031179190534-094724",
    verificationUrl: "",
    image: "certificates/sora ai.jpg",
    relatedProject: "",
    featured: false
  },
  {
    id: "wadhwani-ai-fundamentals",
    title: "Fundamentals of Artificial Intelligence (Basic Level)",
    organization: "Wadhwani Foundation (Wadhwani AI)",
    category: "COURSES",
    type: "Foundation Certification",
    date: "July 4, 2026",
    duration: "7.5 Hours Training",
    role: "Student Learner",
    achievement: "Demonstrated fundamental knowledge of AI concepts and practical applications",
    description: "Structured learning program on foundational concepts, practical use cases, and core models of Artificial Intelligence.",
    skills: ["AI Fundamentals", "Machine Learning Concepts", "Applied AI"],
    credentialId: "ECLYLHDVmn",
    verificationUrl: "",
    image: "certificates/fundamentals of AI.jpg",
    relatedProject: "",
    featured: false
  },
  {
    id: "hack-hustle-hackathon",
    title: "HACK HUSTLE 2.0 National Level Hackathon",
    organization: "Saveetha Engineering College & Institution's Innovation Council (IIC)",
    category: "HACKATHONS",
    type: "Hackathon Recognition",
    date: "April 29 – 30, 2026",
    duration: "24-Hour Hackathon",
    role: "Team Lead — Team Neural Nexus",
    achievement: "Successfully built & presented prototype during 24-hour national hackathon challenge",
    description: "Honorable certificate of participation presented to Team Neural Nexus for designing and pitching a technological innovation during Hack Hustle 2.0.",
    skills: ["Hackathon", "Team Leadership", "Rapid Prototyping", "Pitch Presentation", "IoT / Web Systems"],
    credentialId: "HH2.0-2026-NEURAL",
    verificationUrl: "",
    image: "certificates/compatitions/Hack_Hustle_2.0.jpg",
    relatedProject: "RYDEX Smart Helmet",
    featured: true
  },
  {
    id: "sdgthon-hackathon",
    title: "SDGTHON Sustainable Development Goals Innovation Challenge",
    organization: "Panimalar Engineering College / Innovation Cell",
    category: "ACHIEVEMENT",
    type: "Competition Award",
    date: "2026",
    duration: "Hackathon Event",
    role: "Project Innovator",
    achievement: "Recognized for IoT hardware safety project contributing to UN Sustainable Development Goal #3 (Good Health & Well-being)",
    description: "Awarded recognition during the SDG Innovation Challenge for presenting the RYDEX Smart Helmet system engineered for rider safety and emergency medical alerts.",
    skills: ["Sustainable Technology", "IoT Hardware", "UN SDGs", "Public Safety Tech"],
    credentialId: "SDG-2026-PEC-KV",
    verificationUrl: "",
    image: "certificates/compatitions/poster_project.jpg",
    relatedProject: "RYDEX Smart Helmet",
    featured: true
  },
  {
    id: "greatlearning-embedded-systems",
    title: "Free Embedded Systems Course",
    organization: "Great Learning Academy",
    category: "COURSES",
    type: "Course Certificate",
    date: "April 3, 2026",
    duration: "Self-Paced Course",
    role: "Learner",
    achievement: "Completed training on embedded architecture, microcontrollers, and firmware principles",
    description: "Foundational training covering microcontroller architectures, GPIO operations, timers, and embedded system design fundamentals.",
    skills: ["Embedded Systems", "Microcontrollers", "Firmware", "Embedded C"],
    credentialId: "10046828",
    verificationUrl: "",
    image: "certificates/pdf_img_Certificate AItools_p1_0.png",
    relatedProject: "RYDEX Smart Helmet",
    featured: false
  },
  {
    id: "greatlearning-github-copilot",
    title: "GitHub Copilot Fundamentals",
    organization: "Great Learning Academy",
    category: "COURSES",
    type: "Course Certificate",
    date: "April 3, 2026",
    duration: "Self-Paced Course",
    role: "Learner",
    achievement: "Mastered AI-assisted pair programming workflows using GitHub Copilot",
    description: "Technical training on leveraging generative AI tools in Visual Studio Code for accelerated code generation, test generation, and refactoring.",
    skills: ["GitHub Copilot", "AI Pair Programming", "VS Code Tools", "Developer Productivity"],
    credentialId: "10047043",
    verificationUrl: "",
    image: "certificates/pdf_img_Certificate AItools_p1_0.png",
    relatedProject: "",
    featured: false
  },
  {
    id: "greatlearning-prompt-engineering",
    title: "Introduction to Prompt Engineering",
    organization: "Great Learning Academy",
    category: "COURSES",
    type: "Course Certificate",
    date: "March 15, 2026",
    duration: "Self-Paced Course",
    role: "Learner",
    achievement: "Learned zero-shot, few-shot, and chain-of-thought prompt design for LLMs",
    description: "Structured course detailing effective prompt construction techniques for Large Language Models (LLMs) and automated workflows.",
    skills: ["Prompt Engineering", "LLMs", "Generative AI", "AI Workflows"],
    credentialId: "9963405",
    verificationUrl: "",
    image: "certificates/pdf_img_Certificate AItools_p1_0.png",
    relatedProject: "Level Up",
    featured: false
  },
  {
    id: "greatlearning-intro-iot",
    title: "Introduction to IoT",
    organization: "Great Learning Academy",
    category: "COURSES",
    type: "Course Certificate",
    date: "March 11, 2026",
    duration: "Self-Paced Course",
    role: "Learner",
    achievement: "Completed concepts of IoT node communication, sensors, and cloud telemetry",
    description: "Educational course introducing Internet of Things architecture, wireless communication protocols, and sensor data acquisition.",
    skills: ["Internet of Things", "Sensors", "Wireless Telemetry", "ESP32 / ESP-NOW"],
    credentialId: "9949188",
    verificationUrl: "",
    image: "certificates/pdf_img_Certificate AItools_p1_0.png",
    relatedProject: "RYDEX Smart Helmet",
    featured: false
  },
  {
    id: "greatlearning-intro-matlab",
    title: "Become a Machine Learning Expert: Introduction to MATLAB",
    organization: "Great Learning Academy",
    category: "COURSES",
    type: "Course Certificate",
    date: "March 11, 2026",
    duration: "Self-Paced Course",
    role: "Learner",
    achievement: "Learned numerical computing, matrix data processing, and signal plotting in MATLAB",
    description: "Training in MATLAB matrix operations, data visualization, and basic signal analysis for engineering problem solving.",
    skills: ["MATLAB", "Numerical Computing", "Data Visualization", "Signal Analysis"],
    credentialId: "9948713",
    verificationUrl: "",
    image: "certificates/pdf_img_Certificate AItools_p1_0.png",
    relatedProject: "",
    featured: false
  },
  {
    id: "be10x-ai-tools-workshop",
    title: "AI Tools and ChatGPT Hands-On Workshop",
    organization: "be10x Innovation Studio",
    category: "WORKSHOPS",
    type: "Workshop Certificate",
    date: "2026",
    duration: "Hands-on Masterclass",
    role: "Workshop Attendee",
    achievement: "Trained on rapid AI presentation building, automated data analysis, and AI debugging",
    description: "Interactive masterclass conducted by be10x co-founders focused on leveraging ChatGPT and productivity AI tools for engineering workflows.",
    skills: ["ChatGPT", "AI Productivity Tools", "Vibe Coding", "Rapid Prototyping"],
    credentialId: "BE10X-AI-2026",
    verificationUrl: "",
    image: "certificates/pdf_img_Certificate AItools_p1_0.png",
    relatedProject: "",
    featured: false
  }
];
